version: 0.0
os: linux

files:
  - source: app.jar
    destination: /opt/gachi-gacha/backend/staging
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: root

  BeforeInstall:
    - location: scripts/prepare.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/install.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: root

  ValidateService:
    - location: scripts/validate.sh
      timeout: 120
      runas: root
